## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: true
git:
  depth: 99999999

before_install:
  # R
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
  - sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"
  - sudo apt-get update -qq -y
  - sudo apt-get install git r-base r-base-dev r-recommended -y
  # Python
  - (sudo apt-get -qq update && sudo apt-get install -y python python-pip && sudo pip install pandas matplotlib seaborn)
after_success:
  # Push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("BCBI_base")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
